PASS
Timestamp                       (process)[PID]    
2026-05-09 02:40:28.792477-0700  localhost ClickToMin[2905]: [com.click-to-min:lifecycle] dock PID refreshed: 372
2026-05-09 02:40:28.807188-0700  localhost ClickToMin[2905]: [com.click-to-min:lifecycle] dock frame refreshed: {{212, 1111}, {1496, 79}}
2026-05-09 02:40:28.807860-0700  localhost ClickToMin[2905]: [com.click-to-min:lifecycle] global click monitor installed (CGEventTap)
2026-05-09 02:40:28.807863-0700  localhost ClickToMin[2905]: [com.click-to-min:lifecycle] DockWatcher started
2026-05-09 02:40:28.807863-0700  localhost ClickToMin[2905]: [com.click-to-min:lifecycle] permission granted, DockWatcher installed
2026-05-09 02:40:28.808069-0700  localhost ClickToMin[2905]: [com.click-to-min:lifecycle] app launched
